# Generated by Django 4.2.27 on 2026-02-18 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0027_sysinstallmodule'),
        ('user', '0006_alter_secusermaster_txt_parent_company_verified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secusermaster',
            name='cod_home_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_module_users', to='masters.sysinstallmodule'),
        ),
    ]
