# Generated by Django 4.2.27 on 2026-03-12 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionnaries', '0001_initial'),
        ('masters', '0001_initial'),
        ('campaign', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysusermessage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sysusermessage',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='sysusermessage',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='sysusermessage',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sysorgchart',
            name='cod_addr_country',
            field=models.ForeignKey(blank=True, db_column='cod_addr_country', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_country', to='masters.mstcountrycodes'),
        ),
        migrations.AddField(
            model_name='sysorgchart',
            name='cod_address_state',
            field=models.ForeignKey(blank=True, db_column='cod_address_state', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_state', to='masters.mststatecodes'),
        ),
        migrations.AddField(
            model_name='sysorgchart',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sysorgchart',
            name='id_parent_company',
            field=models.ForeignKey(blank=True, db_column='id_parent_company', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s', to='campaign.mstthirdparties'),
        ),
        migrations.AddField(
            model_name='sysorgchart',
            name='parent_org_unit',
            field=models.ForeignKey(blank=True, db_column='parent_org_unit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='masters.sysorgchart'),
        ),
        migrations.AddField(
            model_name='sysorgchart',
            name='txt_addr_city',
            field=models.ForeignKey(blank=True, db_column='txt_addr_city', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_city', to='masters.mstcityclasses'),
        ),
        migrations.AddField(
            model_name='sysorgchart',
            name='txt_addr_pin',
            field=models.ForeignKey(blank=True, db_column='txt_addr_pin', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_pincodes', to='masters.mstpincodes'),
        ),
        migrations.AddField(
            model_name='sysorgchart',
            name='txt_credit_officer_id',
            field=models.ForeignKey(blank=True, db_column='txt_credit_officer_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_credit_officer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sysorgchart',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, db_column='txt_last_checker_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='sysorgchart',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, db_column='txt_last_maker_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='sysorgchart',
            name='txt_org_manager_id',
            field=models.ForeignKey(blank=True, db_column='txt_org_manager_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sysorgchart',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sysemailtemplates',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sysemailtemplates',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='sysemailtemplates',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='sysemailtemplates',
            name='txt_send_replies_to_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies_from_template', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sysemailtemplates',
            name='txt_sender_email_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_email_template', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sysemailtemplates',
            name='txt_stored_proc_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_template_proc', to='campaign.mstqareviewprocedure'),
        ),
        migrations.AddField(
            model_name='sysemailtemplates',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='syscsstheme',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='syscsstheme',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='syscsstheme',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='syscsstheme',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subpackageroles',
            name='cod_user_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licence_package_roles', to='roles.secuserroles'),
        ),
        migrations.AddField(
            model_name='subpackageroles',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subpackageroles',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='subpackageroles',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='subpackageroles',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sublicenceshist',
            name='cod_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licence_history_currency', to='masters.mstcurrency'),
        ),
        migrations.AddField(
            model_name='sublicenceshist',
            name='cod_default_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licence_history_default_role', to='roles.secuserroles'),
        ),
        migrations.AddField(
            model_name='sublicenceshist',
            name='id_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licence_history_campaign', to='campaign.cmpcampaigns'),
        ),
        migrations.AddField(
            model_name='sublicenceshist',
            name='id_questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licence_history_questionnaire', to='questionnaries.cmpquestionnaire'),
        ),
        migrations.AddField(
            model_name='sublicenceshist',
            name='id_third_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licence_history_thirdparty', to='campaign.mstthirdparties'),
        ),
        migrations.AddField(
            model_name='sublicenceshist',
            name='txt_change_made_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licence_history_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sublicenceshist',
            name='txt_licence_applied_by_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licence_history_licence_applied', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sublicenceshist',
            name='txt_licence_ratified_by_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licence_history_licence_ratified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sublicenceshist',
            name='txt_sale_approved_by_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licence_history_sale_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sublicenceshist',
            name='txt_sale_closed_by_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licence_history_sale_closed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sublicence',
            name='cod_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_licence_currency', to='masters.mstcurrency'),
        ),
        migrations.AddField(
            model_name='sublicence',
            name='cod_default_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_licence_role', to='roles.secuserroles'),
        ),
        migrations.AddField(
            model_name='sublicence',
            name='id_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_licence_campaign', to='campaign.cmpcampaigns'),
        ),
        migrations.AddField(
            model_name='sublicence',
            name='id_questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_licence_questionnaire', to='questionnaries.cmpquestionnaire'),
        ),
        migrations.AddField(
            model_name='sublicence',
            name='id_third_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_licence_thirdparty', to='campaign.mstthirdparties'),
        ),
        migrations.AddField(
            model_name='sublicence',
            name='txt_cancel_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_cancel_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sublicence',
            name='txt_sale_approved_by_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_sale_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sublicence',
            name='txt_sale_closed_by_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_sale_closed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secmenuoptions',
            name='cod_parent_menu_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_menus', to='masters.secmenuoptions'),
        ),
        migrations.AddField(
            model_name='secmenuoptions',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secmenuoptions',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='secmenuoptions',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='secmenuoptions',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstuserdesignation',
            name='cod_parent_designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_designations_list', to='masters.mstuserdesignation'),
        ),
        migrations.AddField(
            model_name='mstuserdesignation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstuserdesignation',
            name='id_third_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.mstthirdparties'),
        ),
        migrations.AddField(
            model_name='mstuserdesignation',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstuserdesignation',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstuserdesignation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='msttimezone',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='msttimezone',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='msttimezone',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='msttimezone',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mststatecodes',
            name='cod_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='states_list', to='masters.mstcountrycodes'),
        ),
        migrations.AddField(
            model_name='mststatecodes',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mststatecodes',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mststatecodes',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mststatecodes',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstpincodes',
            name='cod_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pincodes', to='masters.mstcountrycodes'),
        ),
        migrations.AddField(
            model_name='mstpincodes',
            name='cod_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pincodes', to='masters.mstdistrictcodes'),
        ),
        migrations.AddField(
            model_name='mstpincodes',
            name='cod_state_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pincodes', to='masters.mststatecodes'),
        ),
        migrations.AddField(
            model_name='mstpincodes',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstpincodes',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstpincodes',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstpincodes',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstmajorcity',
            name='cod_city_class',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='major_city', to='masters.mstcityclasses'),
        ),
        migrations.AddField(
            model_name='mstmajorcity',
            name='cod_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='major_cities_lists_country', to='masters.mstcountrycodes'),
        ),
        migrations.AddField(
            model_name='mstmajorcity',
            name='cod_state_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='major_cities_lists_state', to='masters.mststatecodes'),
        ),
        migrations.AddField(
            model_name='mstmajorcity',
            name='cod_time_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='major_cities', to='masters.msttimezone'),
        ),
        migrations.AddField(
            model_name='mstmajorcity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstmajorcity',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstmajorcity',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstmajorcity',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstlanguages',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstlanguages',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstlanguages',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstlanguages',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstdistrictcodes',
            name='cod_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='districts_list_country', to='masters.mstcountrycodes'),
        ),
        migrations.AddField(
            model_name='mstdistrictcodes',
            name='cod_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='districts_list_state', to='masters.mststatecodes'),
        ),
        migrations.AddField(
            model_name='mstdistrictcodes',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstdistrictcodes',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstdistrictcodes',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstdistrictcodes',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstdisclosures',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstdisclosures',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstdisclosures',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstdisclosures',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstdisclosurelang',
            name='cod_disclosure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disclosure_lang', to='masters.mstdisclosures'),
        ),
        migrations.AddField(
            model_name='mstdisclosurelang',
            name='cod_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disclosure_lang', to='masters.mstlanguages'),
        ),
        migrations.AddField(
            model_name='mstdisclosurelang',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstdisclosurelang',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstdisclosurelang',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstdisclosurelang',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstdisabilitycodes',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstdisabilitycodes',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstdisabilitycodes',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstdisabilitycodes',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstdepartmentsupportteam',
            name='cod_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_support_team', to='masters.mstdepartments'),
        ),
        migrations.AddField(
            model_name='mstdepartmentsupportteam',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstdepartmentsupportteam',
            name='id_third_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='departments_support_team', to='campaign.mstthirdparties'),
        ),
        migrations.AddField(
            model_name='mstdepartmentsupportteam',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstdepartmentsupportteam',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstdepartmentsupportteam',
            name='txt_login_id',
            field=models.ForeignKey(blank=True, db_column='txt_login_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_team_memberships', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstdepartmentsupportteam',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstdepartments',
            name='cod_parent_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_departments', to='masters.mstdepartments'),
        ),
        migrations.AddField(
            model_name='mstdepartments',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstdepartments',
            name='id_third_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='departments', to='campaign.mstthirdparties'),
        ),
        migrations.AddField(
            model_name='mstdepartments',
            name='txt_dept_deputy_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_dept_deputy_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstdepartments',
            name='txt_dept_head_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_dept_head_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstdepartments',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstdepartments',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstdepartments',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstcurrency',
            name='cod_country',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_currency', to='masters.mstcountrycodes'),
        ),
        migrations.AddField(
            model_name='mstcurrency',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstcurrency',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstcurrency',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstcurrency',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstcreditofficerlevels',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstcreditofficerlevels',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstcreditofficerlevels',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstcreditofficerlevels',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstcountrycodes',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstcountrycodes',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstcountrycodes',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstcountrycodes',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstcityclasses',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstcityclasses',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstcityclasses',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstcityclasses',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstaudittypes',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstaudittypes',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstaudittypes',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstaudittypes',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstauditchecklist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstauditchecklist',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstauditchecklist',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstauditchecklist',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstaddrtypes',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstaddrtypes',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstaddrtypes',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstaddrtypes',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='sysusermessage',
            unique_together={('num_message', 'cod_language', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='sysorgchart',
            unique_together={('cod_org_unit', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='sysemailtemplates',
            unique_together={('cod_email_template', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='syscsstheme',
            unique_together={('cod_theme', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='subpackageroles',
            unique_together={('cod_licence_package', 'cod_user_role')},
        ),
        migrations.AlterUniqueTogether(
            name='sublicenceshist',
            unique_together={('cod_licence_package', 'id_third_party', 'dat_licence_from', 'dat_time_change')},
        ),
        migrations.AlterUniqueTogether(
            name='sublicence',
            unique_together={('cod_licence_package', 'id_third_party', 'dat_licence_from')},
        ),
        migrations.AlterUniqueTogether(
            name='secmenuoptions',
            unique_together={('cod_menu_option', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstuserdesignation',
            unique_together={('cod_designation', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='msttimezone',
            unique_together={('cod_time_zone', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mststatecodes',
            unique_together={('cod_state', 'cod_country', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstpincodes',
            unique_together={('cod_pin_code', 'cod_country', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstmajorcity',
            unique_together={('cod_city', 'cod_country', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstlanguages',
            unique_together={('cod_language', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstdistrictcodes',
            unique_together={('cod_district', 'cod_state', 'cod_country', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstdisclosures',
            unique_together={('cod_disclosure', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstdisclosurelang',
            unique_together={('cod_disclosure', 'cod_language', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstdisabilitycodes',
            unique_together={('cod_disability', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstdepartmentsupportteam',
            unique_together={('cod_department', 'cod_rec_status', 'id_third_party')},
        ),
        migrations.AlterUniqueTogether(
            name='mstdepartments',
            unique_together={('cod_department', 'id_third_party', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstcurrency',
            unique_together={('cod_currency', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstcreditofficerlevels',
            unique_together={('cod_credit_officer_level', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstcountrycodes',
            unique_together={('cod_country', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstcityclasses',
            unique_together={('cod_city_class', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstaudittypes',
            unique_together={('cod_audit_type', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstauditchecklist',
            unique_together={('cod_audit_item', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstaddrtypes',
            unique_together={('cod_addr_type', 'cod_rec_status')},
        ),
    ]
