# Generated by Django 4.2.27 on 2026-02-18 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0025_sysemailtemplates'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysUserMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_message', models.SmallIntegerField()),
                ('txt_user_message', models.CharField(blank=True, max_length=255, null=True)),
                ('enu_msg_type', models.CharField(choices=[('S', 'Success'), ('I', 'Information'), ('E', 'Error'), ('W', 'Warning')], default='I', max_length=1)),
                ('flg_use_as_alert', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('txt_btn_ok', models.CharField(blank=True, max_length=48, null=True)),
                ('txt_btn_cancel', models.CharField(blank=True, max_length=48, null=True)),
                ('txt_btn_other_1', models.CharField(blank=True, max_length=48, null=True)),
                ('txt_btn_other_2', models.CharField(blank=True, max_length=48, null=True)),
                ('txt_btn_other_3', models.CharField(blank=True, max_length=48, null=True)),
                ('cod_rec_status', models.CharField(choices=[('A', 'Active'), ('N', 'New'), ('M', 'Modified'), ('R', 'Reviewed'), ('C', 'Cancelled'), ('X', 'Deleted')], max_length=1)),
                ('dat_last_maker', models.DateField(blank=True, null=True)),
                ('dat_last_checker', models.DateField(blank=True, null=True)),
                ('cod_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_message_language', to='masters.mstlanguages')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('txt_last_checker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id')),
                ('txt_last_maker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System User Message',
                'verbose_name_plural': 'System User Messages',
                'db_table': 'sys_user_messages',
                'unique_together': {('num_message', 'cod_language', 'cod_rec_status')},
            },
        ),
    ]
