# Generated by Django 4.2.27 on 2026-02-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0026_sysusermessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysInstallModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_module', models.CharField(max_length=4)),
                ('txt_module_name', models.CharField(max_length=48)),
                ('txt_module_home_page', models.CharField(blank=True, max_length=96, null=True)),
                ('txt_module_logo_file', models.CharField(max_length=255)),
                ('txt_bank_name', models.CharField(max_length=96)),
                ('id_licensee_third_party', models.BigIntegerField(blank=True, default=0, null=True)),
                ('dat_license_start', models.DateField(blank=True, null=True)),
                ('dat_license_expire', models.DateField(blank=True, null=True)),
                ('txt_module_param_1', models.CharField(blank=True, max_length=96, null=True)),
                ('txt_module_param_2', models.CharField(blank=True, max_length=96, null=True)),
                ('txt_module_param_3', models.CharField(blank=True, max_length=96, null=True)),
                ('txt_module_key', models.CharField(blank=True, max_length=255, null=True)),
                ('txt_selfserv_t_and_c_url', models.CharField(blank=True, max_length=255, null=True)),
                ('flg_default_value', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
            ],
            options={
                'verbose_name': 'Installed Module',
                'verbose_name_plural': 'Installed Modules',
                'db_table': 'sys_install_modules',
            },
        ),
    ]
