# Generated by Django 4.2.27 on 2026-02-18 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaries', '0019_cmpquestion_txt_last_checker_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign', '0039_alter_cmpcampaigns_id_commissioned_by_thirdparty'),
        ('roles', '0006_alter_secuserrolemenus_cod_menu_option_and_more'),
        ('masters', '0029_subpackageroles'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubLicencesHist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cod_licence_package', models.CharField(max_length=4)),
                ('dat_licence_from', models.DateField()),
                ('dat_time_change', models.DateTimeField()),
                ('dat_licence_to', models.DateField(blank=True, null=True)),
                ('txt_licence_key', models.CharField(blank=True, max_length=255, null=True)),
                ('num_max_users', models.SmallIntegerField(blank=True, null=True)),
                ('num_max_locations', models.SmallIntegerField(blank=True, null=True)),
                ('num_tier', models.SmallIntegerField(blank=True, null=True)),
                ('dat_licence_applied', models.DateField(blank=True, null=True)),
                ('dat_licence_ratified', models.DateField(blank=True, null=True)),
                ('flg_licence_ratified', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('amt_rack_rate', models.FloatField(blank=True, null=True)),
                ('amt_charged_rate', models.FloatField(blank=True, null=True)),
                ('enu_billing_frequency', models.CharField(blank=True, choices=[('R', 'Recurring'), ('D', 'Daily'), ('W', 'Weekly'), ('F', 'Fortnightly'), ('M', 'Monthly'), ('Q', 'Quarterly'), ('H', 'Half-Yearly'), ('A', 'Annual'), ('B', 'Biannual'), ('X', 'None')], max_length=1, null=True)),
                ('dat_sale_closed', models.DateField(blank=True, null=True)),
                ('dat_sale_approved', models.DateField(blank=True, null=True)),
                ('cod_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licence_history_currency', to='masters.mstcurrency')),
                ('cod_default_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licence_history_default_role', to='roles.secuserroles')),
                ('id_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licence_history_campaign', to='campaign.cmpcampaigns')),
                ('id_questionnaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licence_history_questionnaire', to='questionnaries.cmpquestionnaire')),
                ('id_third_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licence_history_thirdparty', to='campaign.mstthirdparties')),
                ('txt_change_made_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licence_history_changes', to=settings.AUTH_USER_MODEL)),
                ('txt_licence_applied_by_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licence_history_licence_applied', to=settings.AUTH_USER_MODEL)),
                ('txt_licence_ratified_by_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licence_history_licence_ratified', to=settings.AUTH_USER_MODEL)),
                ('txt_sale_approved_by_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licence_history_sale_approved', to=settings.AUTH_USER_MODEL)),
                ('txt_sale_closed_by_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licence_history_sale_closed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sub_licences_hist',
                'unique_together': {('cod_licence_package', 'id_third_party', 'dat_licence_from', 'dat_time_change')},
            },
        ),
    ]
