# Generated by Django 4.2.27 on 2026-03-02 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0041_alter_cmpemail_cod_channel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0030_sublicenceshist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysOrgChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_org_unit', models.CharField(max_length=8)),
                ('txt_org_unit_name', models.CharField(blank=True, max_length=48, null=True)),
                ('flg_backoffice', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('flg_rollup_unit', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('flg_accept_selfserv_appl', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('cod_service_branch', models.CharField(blank=True, max_length=8, null=True)),
                ('txt_ifsc_code', models.CharField(blank=True, max_length=48, null=True)),
                ('txt_addr_line1', models.CharField(blank=True, max_length=96, null=True)),
                ('txt_addr_line2', models.CharField(blank=True, max_length=96, null=True)),
                ('txt_addr_line3', models.CharField(blank=True, max_length=96, null=True)),
                ('txt_org_unit_email', models.EmailField(blank=True, max_length=96, null=True)),
                ('txt_org_unit_phone', models.CharField(blank=True, max_length=16, null=True)),
                ('num_clearing_house_gl', models.BigIntegerField(blank=True, null=True)),
                ('cod_storage_location', models.CharField(blank=True, default='', max_length=4)),
                ('cod_rec_status', models.CharField(choices=[('A', 'Active'), ('N', 'New'), ('M', 'Modified'), ('R', 'Reviewed'), ('C', 'Cancelled'), ('X', 'Deleted')], default='A', max_length=1)),
                ('dat_last_maker', models.DateField(blank=True, null=True)),
                ('dat_last_checker', models.DateField(blank=True, null=True)),
                ('cod_addr_country', models.ForeignKey(blank=True, db_column='cod_addr_country', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_country', to='masters.mstcountrycodes')),
                ('cod_address_state', models.ForeignKey(blank=True, db_column='cod_address_state', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_state', to='masters.mststatecodes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('id_parent_company', models.ForeignKey(blank=True, db_column='id_parent_company', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s', to='campaign.mstthirdparties')),
                ('parent_org_unit', models.ForeignKey(blank=True, db_column='parent_org_unit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='masters.sysorgchart')),
                ('txt_addr_city', models.ForeignKey(blank=True, db_column='txt_addr_city', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_city', to='masters.mstcityclasses')),
                ('txt_addr_pin', models.ForeignKey(blank=True, db_column='txt_addr_pin', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_pincodes', to='masters.mstpincodes')),
                ('txt_credit_officer_id', models.ForeignKey(blank=True, db_column='txt_credit_officer_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_credit_officer', to=settings.AUTH_USER_MODEL)),
                ('txt_last_checker_id', models.ForeignKey(blank=True, db_column='txt_last_checker_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id')),
                ('txt_last_maker_id', models.ForeignKey(blank=True, db_column='txt_last_maker_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id')),
                ('txt_org_manager_id', models.ForeignKey(blank=True, db_column='txt_org_manager_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_manager', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sys_org_chart',
                'unique_together': {('cod_org_unit', 'cod_rec_status')},
            },
        ),
    ]
