version: "3.9"

services:

  web:
    build: .
    container_name: django_app
    command: bash start.sh
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: satisactual_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: