# Generated by Django 4.2.27 on 2026-02-13 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_secuserroledisclosures_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secuserroledisclosures',
            name='cod_user_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_disclosures', to='roles.secuserroles', to_field='cod_user_role'),
        ),
        migrations.AlterField(
            model_name='secuserrolemenus',
            name='cod_user_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_menus', to='roles.secuserroles', to_field='cod_user_role'),
        ),
        migrations.AlterField(
            model_name='secuserroles',
            name='cod_user_role',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='secuserxroles',
            name='cod_user_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_x_roles', to='roles.secuserroles', to_field='cod_user_role'),
        ),
    ]
