# Generated by Django 4.2.27 on 2026-02-13 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_alter_secuserroledisclosures_cod_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secuserroledisclosures',
            name='cod_user_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_disclosures', to='roles.secuserroles'),
        ),
        migrations.AlterField(
            model_name='secuserrolemenus',
            name='cod_user_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_menus', to='roles.secuserroles'),
        ),
        migrations.AlterField(
            model_name='secuserxroles',
            name='cod_user_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_x_roles', to='roles.secuserroles'),
        ),
    ]
