# Generated by Django 4.2.27 on 2026-02-17 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0025_sysemailtemplates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roles', '0005_alter_secuserroledisclosures_cod_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secuserrolemenus',
            name='cod_menu_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_role_menus', to='masters.secmenuoptions'),
        ),
        migrations.AlterField(
            model_name='secuserroles',
            name='cod_home_menu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_home_menu', to='masters.secmenuoptions'),
        ),
        migrations.AlterField(
            model_name='secuserxroles',
            name='txt_login_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_x_roles', to=settings.AUTH_USER_MODEL),
        ),
    ]
