# Generated by Django 4.2.27 on 2026-02-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0006_alter_secuserrolemenus_cod_menu_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secuserrolemenus',
            name='flg_create',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='secuserrolemenus',
            name='flg_delete',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='secuserrolemenus',
            name='flg_update',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='secuserrolemenus',
            name='flg_view',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1),
        ),
    ]
