# Generated by Django 4.2.27 on 2026-02-20 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0007_secuserrolemenus_flg_create_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secuserrolemenus',
            old_name='flg_view',
            new_name='flg_get',
        ),
        migrations.RenameField(
            model_name='secuserrolemenus',
            old_name='flg_create',
            new_name='flg_post',
        ),
        migrations.RenameField(
            model_name='secuserrolemenus',
            old_name='flg_update',
            new_name='flg_put',
        ),
    ]
