FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Install system dependencies for mysqlclient
RUN apt-get update && apt-get install -y \
    gcc \
    default-libmysqlclient-dev \
    pkg-config \
    netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --upgrade pip \
    && pip install -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["bash","start.sh"]
ubuntu@ip-172-31-10-49:~/Demo_Project-Satisactual$ car docker-compose.yml 
Command 'car' not found, but can be installed with:
sudo apt install ucommon-utils
ubuntu@ip-172-31-10-49:~/Demo_Project-Satisactual$ cat docker-compose.yml 
version: "3"

services:

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: satisactual_db
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3306:3306"

  web:
    build: .
    container_name: django_app
    command: bash start.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
ubuntu@ip-172-31-10-49:~/Demo_Project-Satisactual$ ls
Dockerfile  README.md  api  docker-compose.yml  manage.py  requirements.txt  satisactual  site  start.sh  utils
ubuntu@ip-172-31-10-49:~/Demo_Project-Satisactual$ cd satisactual/
ubuntu@ip-172-31-10-49:~/Demo_Project-Satisactual/satisactual$ ls
__init__.py  __pycache__  asgi.py  celery.py  settings.py  urls.py  wsgi.py
ubuntu@ip-172-31-10-49:~/Demo_Project-Satisactual/satisactual$ nano settings.py 
ubuntu@ip-172-31-10-49:~/Demo_Project-Satisactual/satisactual$ cat settings.py 

"""
Django settings for satisactual project.
Generated by 'django-admin startproject' using Django 5.2.9
"""

from pathlib import Path
from datetime import timedelta

# --------------------------------------------------
# BASE CONFIG
# --------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-(yex+l=m4t-g$s478zfb1ey3$^73yk)(5yfc&%nz5@6gl(p9el'

DEBUG = True

# --------------------------------------------------
# ALLOWED HOSTS
# --------------------------------------------------

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "35.154.191.30",
    # "15.207.254.161"
    "3.110.191.93"
]

# --------------------------------------------------
# CORS & CSRF (ANGULAR SAFE)
# --------------------------------------------------

INSTALLED_APPS = [
    'corsheaders',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_yasg',

    'api.roles',
    'api.masters',
    'api.campaign',
    'api.contact',
    'api.user',
    'api.auth',
    'api.questionnaries',
    'api.product',
]

# CELERY CONFIGURATION

CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

CELERY_TIMEZONE = "Asia/Kolkata"

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',   # MUST BE FIRST
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",
    "http://127.0.0.1:4200",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://35.154.191.30",
    "http://127.0.0.1:5500",   # ✅ REQUIRED
    "http://localhost:5500",
]

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:4200",
    "http://127.0.0.1:4200",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://35.154.191.30",
    "http://127.0.0.1:5500",   # ✅ REQUIRED
    "http://localhost:5500",
]

# --------------------------------------------------
# URLS / TEMPLATES
# --------------------------------------------------

ROOT_URLCONF = 'satisactual.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'satisactual.wsgi.application'

# --------------------------------------------------
# DATABASE (MySQL)
# --------------------------------------------------

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'satisactual_db',
        'HOST': 'mysql_db',
        'PORT': '3306',
        'USER': 'root',
        'PASSWORD': 'root123',
        'OPTIONS': {
            'init_command': 'SET sql_mode="STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION"',
        },
    }
}

# --------------------------------------------------
# AUTH / USER MODEL
# --------------------------------------------------

AUTH_USER_MODEL = 'user.SecUserMaster'

# --------------------------------------------------
# DJANGO REST FRAMEWORK
# --------------------------------------------------


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',  # Required for handling file uploads
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "api.auth.permissions.RoleBasedMenuPermission",
    ]
}

# --------------------------------------------------
# JWT SETTINGS
# --------------------------------------------------

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# --------------------------------------------------
# SWAGGER SETTINGS
# --------------------------------------------------

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': 'JWT Authorization header. Example: Bearer <token>',
        }
    },
    'USE_SESSION_AUTH': False,
}

# --------------------------------------------------
# PASSWORD VALIDATION
# --------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# --------------------------------------------------
# INTERNATIONALIZATION
# --------------------------------------------------

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True

# --------------------------------------------------
# STATIC FILES
# --------------------------------------------------

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py

MEDIA_ROOT = BASE_DIR / "site"
MEDIA_URL = "/site/"