# Generated by Django 4.2.27 on 2026-03-12 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
        ('masters', '0001_initial'),
        ('questionnaries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syspersonalizationtags',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='syspersonalizationtags',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='syspersonalizationtags',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='syspersonalizationtags',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstthirdpartytypes',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstthirdpartytypes',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstthirdpartytypes',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstthirdpartytypes',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstthirdparties',
            name='cod_addr_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_party_state', to='masters.mstcountrycodes'),
        ),
        migrations.AddField(
            model_name='mstthirdparties',
            name='cod_address_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_party_state', to='masters.mststatecodes'),
        ),
        migrations.AddField(
            model_name='mstthirdparties',
            name='cod_third_party_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_parties', to='campaign.mstthirdpartytypes'),
        ),
        migrations.AddField(
            model_name='mstthirdparties',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstthirdparties',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstthirdparties',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstthirdparties',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstcampaigntypes',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstcampaigntypes',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstcampaigntypes',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstcampaigntypes',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstcampaignteamrole',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstcampaignteamrole',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstcampaignteamrole',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstcampaignteamrole',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpwaves',
            name='cod_css_theme',
            field=models.ForeignKey(blank=True, db_column='cod_css_theme', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waves', to='masters.syscsstheme'),
        ),
        migrations.AddField(
            model_name='cmpwaves',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpwaves',
            name='id_campaign',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wave', to='campaign.cmpcampaigns'),
        ),
        migrations.AddField(
            model_name='cmpwaves',
            name='id_contact_list',
            field=models.ForeignKey(blank=True, db_column='id_contact_list', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waves', to='contact.cmpcontactlist'),
        ),
        migrations.AddField(
            model_name='cmpwaves',
            name='id_questionnaire',
            field=models.ForeignKey(blank=True, db_column='id_questionnaire', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waves', to='questionnaries.cmpquestionnaire'),
        ),
        migrations.AddField(
            model_name='cmpwaves',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='cmpwaves',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='cmpwaves',
            name='txt_wave_delivery_head_id',
            field=models.ForeignKey(blank=True, db_column='txt_wave_delivery_head_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wave_delivery_head', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpwaves',
            name='txt_wave_requisitioner_id',
            field=models.ForeignKey(blank=True, db_column='txt_wave_requisitioner_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wave_requisitioner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpwaves',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpteam',
            name='cod_preferred_lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cam_team_lang', to='masters.mstlanguages'),
        ),
        migrations.AddField(
            model_name='cmpteam',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpteam',
            name='id_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='campaign.cmpcampaigns'),
        ),
        migrations.AddField(
            model_name='cmpteam',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='cmpteam',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='cmpteam',
            name='txt_login_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_teams', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='cmpteam',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpsegmentsize',
            name='cod_option',
            field=models.ForeignKey(blank=True, db_column='cod_option', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='segment_sizes', to='questionnaries.cmpquestionoptions'),
        ),
        migrations.AddField(
            model_name='cmpsegmentsize',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpsegmentsize',
            name='id_campaign',
            field=models.ForeignKey(blank=True, db_column='id_campaign', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='segment_sizes', to='campaign.cmpcampaigns'),
        ),
        migrations.AddField(
            model_name='cmpsegmentsize',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, db_column='txt_last_checker_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segment_size_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='cmpsegmentsize',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, db_column='txt_last_maker_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segment_size_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='cmpsegmentsize',
            name='txt_segment_name',
            field=models.ForeignKey(blank=True, db_column='txt_segment_name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='segment_sizes', to='campaign.cmpsegment'),
        ),
        migrations.AddField(
            model_name='cmpsegmentsize',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpsegment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpsegment',
            name='id_campaign',
            field=models.ForeignKey(blank=True, db_column='id_campaign', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cmp_segments', to='campaign.cmpcampaigns'),
        ),
        migrations.AddField(
            model_name='cmpsegment',
            name='id_qualifying_question',
            field=models.ForeignKey(blank=True, db_column='id_qualifying_question', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmp_segments', to='questionnaries.cmpquestion'),
        ),
        migrations.AddField(
            model_name='cmpsegment',
            name='num_contact_list_col',
            field=models.ForeignKey(blank=True, db_column='num_contact_list_col', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_segment', to='contact.cmpcontactlistcolumns'),
        ),
        migrations.AddField(
            model_name='cmpsegment',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='cmpsegment',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='cmpsegment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpemail',
            name='cod_channel',
            field=models.ForeignKey(blank=True, db_column='cod_channel', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='contact.mstcontactchannel'),
        ),
        migrations.AddField(
            model_name='cmpemail',
            name='cod_language',
            field=models.ForeignKey(blank=True, db_column='cod_language', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='masters.mstlanguages'),
        ),
        migrations.AddField(
            model_name='cmpemail',
            name='id_campaign',
            field=models.ForeignKey(blank=True, db_column='id_campaign', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='campaign.cmpcampaigns'),
        ),
        migrations.AddField(
            model_name='cmpemail',
            name='id_campaign_wave',
            field=models.ForeignKey(blank=True, db_column='id_campaign_wave', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='campaign.cmpwaves'),
        ),
        migrations.AddField(
            model_name='cmpemail',
            name='txt_approved_by_id',
            field=models.ForeignKey(blank=True, db_column='txt_approved_by_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpemail',
            name='txt_composed_by_id',
            field=models.ForeignKey(blank=True, db_column='txt_composed_by_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_composed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpcampaignxchannels',
            name='cod_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_x_channel', to='contact.mstcontactchannel'),
        ),
        migrations.AddField(
            model_name='cmpcampaignxchannels',
            name='id_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_x_channel', to='campaign.cmpcampaigns'),
        ),
        migrations.AddField(
            model_name='cmpcampaignxchannels',
            name='txt_cmp_chnl_manager_id',
            field=models.ForeignKey(blank=True, db_column='txt_cmp_chnl_manager_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpcampaignusergeocoverage',
            name='cod_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaign_geo_coverage', to='masters.mstcountrycodes'),
        ),
        migrations.AddField(
            model_name='cmpcampaignusergeocoverage',
            name='cod_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaign_geo_coverage', to='masters.mstdistrictcodes'),
        ),
        migrations.AddField(
            model_name='cmpcampaignusergeocoverage',
            name='cod_pin_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaign_geo_coverage', to='masters.mstpincodes'),
        ),
        migrations.AddField(
            model_name='cmpcampaignusergeocoverage',
            name='cod_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaign_geo_coverage', to='masters.mststatecodes'),
        ),
        migrations.AddField(
            model_name='cmpcampaignusergeocoverage',
            name='id_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaign_geo_coverage', to='campaign.cmpcampaigns'),
        ),
        migrations.AddField(
            model_name='cmpcampaignusergeocoverage',
            name='txt_login_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaign_geo_coverage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpcampaignscripts',
            name='cod_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaign_scripts', to='contact.mstcontactchannel'),
        ),
        migrations.AddField(
            model_name='cmpcampaignscripts',
            name='cod_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaign_scripts', to='masters.mstlanguages'),
        ),
        migrations.AddField(
            model_name='cmpcampaignscripts',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpcampaignscripts',
            name='id_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='campaign.cmpcampaigns'),
        ),
        migrations.AddField(
            model_name='cmpcampaignscripts',
            name='id_campaign_wave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='campaign.cmpwaves'),
        ),
        migrations.AddField(
            model_name='cmpcampaignscripts',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='cmpcampaignscripts',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='cmpcampaignscripts',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpcampaigns',
            name='cod_campaign_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaign', to='campaign.mstcampaigntypes'),
        ),
        migrations.AddField(
            model_name='cmpcampaigns',
            name='cod_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaign', to='masters.mstdepartments'),
        ),
        migrations.AddField(
            model_name='cmpcampaigns',
            name='cod_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaign', to='masters.mstlanguages'),
        ),
        migrations.AddField(
            model_name='cmpcampaigns',
            name='cod_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaign', to='product.mstprodcodes'),
        ),
        migrations.AddField(
            model_name='cmpcampaigns',
            name='cod_promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaign', to='product.mstpromocodes'),
        ),
        migrations.AddField(
            model_name='cmpcampaigns',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdd', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpcampaigns',
            name='id_commissioned_by_thirdparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaigns', to='campaign.mstthirdparties'),
        ),
        migrations.AddField(
            model_name='cmpcampaigns',
            name='id_qa_review_proc',
            field=models.ForeignKey(blank=True, db_column='id_qa_review_proc', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_reviews', to='campaign.mstqareviewprocedure'),
        ),
        migrations.AddField(
            model_name='cmpcampaigns',
            name='txt_camp_mgr_id',
            field=models.ForeignKey(blank=True, db_column='txt_camp_mgr_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpcampaigns',
            name='txt_created_by_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpcampaigns',
            name='txt_invoice_sent_to_id',
            field=models.ForeignKey(blank=True, db_column='txt_invoice_sent_to_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpcampaigns',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='cmpcampaigns',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='cmpcampaigns',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpcampaigngeocoverage',
            name='cod_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='geo_coverage', to='masters.mstcountrycodes'),
        ),
        migrations.AddField(
            model_name='cmpcampaigngeocoverage',
            name='cod_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='geo_coverage', to='masters.mstdistrictcodes'),
        ),
        migrations.AddField(
            model_name='cmpcampaigngeocoverage',
            name='cod_pin_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='geo_coverage', to='masters.mstpincodes'),
        ),
        migrations.AddField(
            model_name='cmpcampaigngeocoverage',
            name='cod_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='geo_coverage', to='masters.mststatecodes'),
        ),
        migrations.AddField(
            model_name='cmpcampaigngeocoverage',
            name='id_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='geo_coverage', to='campaign.cmpcampaigns'),
        ),
        migrations.AddField(
            model_name='cmpcallercredentials',
            name='cod_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cmp_caller_credentials_channel', to='contact.mstcontactchannel'),
        ),
        migrations.AddField(
            model_name='cmpcallercredentials',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpcallercredentials',
            name='txt_caller_authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cmp_caller_credentials_authorized', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpcallercredentials',
            name='txt_caller_base_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cmp_caller_base_city', to='masters.mstcityclasses'),
        ),
        migrations.AddField(
            model_name='cmpcallercredentials',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, db_column='txt_last_checker_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='cmpcallercredentials',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, db_column='txt_last_maker_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='cmpcallercredentials',
            name='txt_login_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cmp_caller_credentials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpcallercredentials',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='syspersonalizationtags',
            unique_together={('cod_tag', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstthirdpartytypes',
            unique_together={('cod_third_party_type', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstthirdparties',
            unique_together={('id_third_party', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstcampaigntypes',
            unique_together={('cod_campaign_type', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstcampaignteamrole',
            unique_together={('cod_team_role', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='cmpwaves',
            unique_together={('id_campaign',)},
        ),
        migrations.AddIndex(
            model_name='cmpteam',
            index=models.Index(fields=['id_campaign'], name='cmp_team_id_camp_3630c2_idx'),
        ),
        migrations.AddIndex(
            model_name='cmpteam',
            index=models.Index(fields=['txt_login_id'], name='cmp_team_txt_log_dd7267_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cmpteam',
            unique_together={('id_campaign', 'txt_login_id', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='cmpsegmentsize',
            unique_together={('id_campaign', 'txt_segment_name', 'cod_rec_status', 'cod_option')},
        ),
        migrations.AlterUniqueTogether(
            name='cmpsegment',
            unique_together={('id_campaign', 'cod_rec_status', 'txt_segment_name')},
        ),
        migrations.AlterUniqueTogether(
            name='cmpemail',
            unique_together={('id_campaign', 'id_campaign_wave', 'cod_language', 'cod_channel')},
        ),
        migrations.AlterUniqueTogether(
            name='cmpcampaignxchannels',
            unique_together={('id_campaign', 'cod_channel')},
        ),
        migrations.AlterUniqueTogether(
            name='cmpcampaignusergeocoverage',
            unique_together={('txt_login_id', 'cod_country', 'cod_state', 'cod_district', 'txt_city_name', 'cod_pin_code', 'id_campaign')},
        ),
        migrations.AddIndex(
            model_name='cmpcampaignscripts',
            index=models.Index(fields=['id_campaign'], name='cmp_campaig_id_camp_672963_idx'),
        ),
        migrations.AddIndex(
            model_name='cmpcampaignscripts',
            index=models.Index(fields=['cod_channel'], name='cmp_campaig_cod_cha_22c557_idx'),
        ),
        migrations.AddIndex(
            model_name='cmpcampaignscripts',
            index=models.Index(fields=['cod_language'], name='cmp_campaig_cod_lan_a06d0f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cmpcampaignscripts',
            unique_together={('id_campaign', 'cod_channel', 'cod_language', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='cmpcampaigngeocoverage',
            unique_together={('id_campaign', 'cod_country', 'cod_state', 'cod_district', 'txt_city_name', 'cod_pin_code')},
        ),
        migrations.AlterUniqueTogether(
            name='cmpcallercredentials',
            unique_together={('txt_login_id', 'cod_rec_status')},
        ),
    ]
