# Generated by Django 4.2.27 on 2026-03-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstcampaigntypes',
            name='cod_campaign_type',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
