# Generated by Django 4.2.27 on 2026-03-02 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0013_cmpcontactsassigned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0030_sublicenceshist'),
        ('campaign', '0039_alter_cmpcampaigns_id_commissioned_by_thirdparty'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmpEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enu_status', models.CharField(blank=True, choices=[('C', 'Composed'), ('A', 'Approved'), ('T', 'Tested')], max_length=1, null=True)),
                ('txt_subject_line', models.CharField(blank=True, max_length=96, null=True)),
                ('txt_email', models.TextField(blank=True, null=True)),
                ('txt_signature_line', models.TextField(blank=True, null=True)),
                ('flg_attach_flyer', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('txt_addl_detail_url', models.CharField(blank=True, max_length=255, null=True)),
                ('txt_bkgrd_img_url', models.CharField(blank=True, max_length=255, null=True)),
                ('txt_sender_email_id', models.CharField(blank=True, max_length=48, null=True)),
                ('txt_send_replies_to_id', models.CharField(blank=True, max_length=48, null=True)),
                ('dat_time_delay_until', models.DateTimeField(blank=True, null=True)),
                ('dat_time_expires_after', models.DateTimeField(blank=True, null=True)),
                ('flg_include_unsubscribe_link', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('txt_unsubscribe_url', models.CharField(blank=True, max_length=255, null=True)),
                ('txt_unsubscribe', models.CharField(blank=True, max_length=255, null=True)),
                ('flg_include_no_replies', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('txt_noreplies', models.CharField(blank=True, max_length=255, null=True)),
                ('flg_request_read_receipt', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('flg_request_delivery_receipt', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('dat_composed', models.DateField(blank=True, null=True)),
                ('dat_approved', models.DateField(blank=True, null=True)),
                ('num_hours_1st_reminder', models.SmallIntegerField(default=72)),
                ('num_hours_2nd_reminder', models.SmallIntegerField(default=168)),
                ('num_reminders', models.SmallIntegerField(default=2)),
                ('flg_include_password', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('id_key_question', models.BigIntegerField(blank=True, null=True)),
                ('cod_channel', models.ForeignKey(blank=True, db_column='channel', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='contact.mstcontactchannel')),
                ('cod_language', models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='masters.mstlanguages')),
                ('id_campaign', models.ForeignKey(blank=True, db_column='campaign', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='campaign.cmpcampaigns')),
                ('id_campaign_wave', models.ForeignKey(blank=True, db_column='campaign_wave', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='campaign.cmpwaves')),
                ('txt_approved_by_id', models.ForeignKey(blank=True, db_column='txt_approved_by_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_approved', to=settings.AUTH_USER_MODEL)),
                ('txt_composed_by_id', models.ForeignKey(blank=True, db_column='txt_composed_by_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_composed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cmp_email',
                'unique_together': {('id_campaign', 'id_campaign_wave', 'cod_language', 'cod_channel')},
            },
        ),
    ]
