# Generated by Django 4.2.27 on 2026-03-02 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0030_sublicenceshist'),
        ('contact', '0013_cmpcontactsassigned'),
        ('campaign', '0040_cmpemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmpemail',
            name='cod_channel',
            field=models.ForeignKey(blank=True, db_column='cod_channel', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='contact.mstcontactchannel'),
        ),
        migrations.AlterField(
            model_name='cmpemail',
            name='cod_language',
            field=models.ForeignKey(blank=True, db_column='cod_language', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='masters.mstlanguages'),
        ),
        migrations.AlterField(
            model_name='cmpemail',
            name='id_campaign',
            field=models.ForeignKey(blank=True, db_column='id_campaign', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='campaign.cmpcampaigns'),
        ),
        migrations.AlterField(
            model_name='cmpemail',
            name='id_campaign_wave',
            field=models.ForeignKey(blank=True, db_column='id_campaign_wave', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='campaign.cmpwaves'),
        ),
    ]
