# Generated by Django 4.2.27 on 2026-03-03 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0013_cmpcontactsassigned'),
        ('campaign', '0041_alter_cmpemail_cod_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmpsegment',
            name='num_contact_list_col',
            field=models.ForeignKey(blank=True, db_column='num_contact_list_col', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_segment', to='contact.cmpcontactlistcolumns'),
        ),
    ]
