# Generated by Django 4.2.27 on 2026-03-12 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign', '0002_initial'),
        ('contact', '0001_initial'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mstcontactoutcome',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstcontactoutcome',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstcontactoutcome',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstcontactoutcome',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstcontactchannel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstcontactchannel',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstcontactchannel',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstcontactchannel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpcontactsassigned',
            name='cod_language',
            field=models.ForeignKey(blank=True, db_column='cod_language', null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.mstlanguages'),
        ),
        migrations.AddField(
            model_name='cmpcontactsassigned',
            name='cod_pref_channel',
            field=models.ForeignKey(blank=True, db_column='cod_pref_channel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_assignments', to='contact.mstcontactchannel'),
        ),
        migrations.AddField(
            model_name='cmpcontactsassigned',
            name='id_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cmp_contact_assigned', to='campaign.cmpcampaigns'),
        ),
        migrations.AddField(
            model_name='cmpcontactsassigned',
            name='id_campaign_wave',
            field=models.ForeignKey(blank=True, db_column='cmp_contact_assigned', null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.cmpwaves'),
        ),
        migrations.AddField(
            model_name='cmpcontactsassigned',
            name='id_contact_list',
            field=models.ForeignKey(blank=True, db_column='id_contact_list', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmp_contact_assigned', to='contact.cmpcontactlist'),
        ),
        migrations.AddField(
            model_name='cmpcontactsassigned',
            name='txt_assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_assigned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpcontactsassigned',
            name='txt_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpcontactsassigned',
            name='txt_deassigned_by_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deassigned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpcontactlistfiles',
            name='id_contact_list',
            field=models.ForeignKey(blank=True, db_column='id_contact_list', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='contact.cmpcontactlist'),
        ),
        migrations.AddField(
            model_name='cmpcontactlistfiles',
            name='txt_file_uploaded_by_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_list_file_uploader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpcontactlistfiles',
            name='txt_list_reviewed_by_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_list_file_reviewer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='cmpcontactlistcolumns',
            unique_together={('num_column',)},
        ),
        migrations.AddField(
            model_name='cmpcontactlist',
            name='txt_list_created_by_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpcontactlist',
            name='txt_list_owner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpcontactlist',
            name='txt_list_reviewed_by_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='mstcontactoutcome',
            unique_together={('cod_contact_outcome', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstcontactchannel',
            unique_together={('cod_channel', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='cmpcontactsassigned',
            unique_together={('id_campaign', 'id_campaign_wave', 'id_contact_list', 'num_list_item', 'txt_assigned_to', 'num_follow_up_level')},
        ),
        migrations.AlterUniqueTogether(
            name='cmpcontactlistfiles',
            unique_together={('id_contact_list', 'txt_upload_file_path', 'txt_upload_file_name', 'dat_time_file_upload_start', 'txt_file_uploaded_by_id')},
        ),
    ]
