# Generated by Django 4.2.27 on 2026-03-12 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionnaries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstquestiontype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstquestiontype',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstquestiontype',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstquestiontype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstquestionclass',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstquestionclass',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstquestionclass',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstquestionclass',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpquestionoptions',
            name='cod_parent_question_option',
            field=models.ForeignKey(blank=True, db_column='cod_parent_question_option', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_options', to='questionnaries.cmpquestionoptions'),
        ),
        migrations.AddField(
            model_name='cmpquestionoptions',
            name='id_parent_question',
            field=models.ForeignKey(blank=True, db_column='id_parent_question', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_question_options', to='questionnaries.cmpquestion'),
        ),
        migrations.AddField(
            model_name='cmpquestionoptions',
            name='id_question',
            field=models.ForeignKey(blank=True, db_column='id_question', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_options', to='questionnaries.cmpquestion'),
        ),
        migrations.AddField(
            model_name='cmpquestionnairequestions',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpquestionnairequestions',
            name='id_prerequisite_options',
            field=models.ManyToManyField(blank=True, related_name='questionnaire_prerequisites', to='questionnaries.cmpquestionoptions'),
        ),
        migrations.AddField(
            model_name='cmpquestionnairequestions',
            name='id_prerequisite_question',
            field=models.ForeignKey(blank=True, db_column='id_prerequisite_question', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_questions', to='questionnaries.cmpquestion'),
        ),
        migrations.AddField(
            model_name='cmpquestionnairequestions',
            name='id_question',
            field=models.ForeignKey(blank=True, db_column='id_question', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_mappings', to='questionnaries.cmpquestion'),
        ),
        migrations.AddField(
            model_name='cmpquestionnairequestions',
            name='id_questionnaire',
            field=models.ForeignKey(blank=True, db_column='id_questionnaire', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_questions', to='questionnaries.cmpquestionnaire'),
        ),
        migrations.AddField(
            model_name='cmpquestionnairequestions',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='cmpquestionnairequestions',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='cmpquestionnairequestions',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpquestionnairequestionoptions',
            name='id_option',
            field=models.ForeignKey(blank=True, db_column='cod_option', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_option_links', to='questionnaries.cmpquestionoptions'),
        ),
        migrations.AddField(
            model_name='cmpquestionnairequestionoptions',
            name='id_question',
            field=models.ForeignKey(blank=True, db_column='id_question', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questionnaries.cmpquestion'),
        ),
        migrations.AddField(
            model_name='cmpquestionnairequestionoptions',
            name='id_questionnaire',
            field=models.ForeignKey(blank=True, db_column='id_questionnaire', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_options', to='questionnaries.cmpquestionnaire'),
        ),
        migrations.AddField(
            model_name='cmpquestionnairequestionoptions',
            name='id_skip_to_question',
            field=models.ForeignKey(blank=True, db_column='id_skip_to_question', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skip_from_options', to='questionnaries.cmpquestion'),
        ),
        migrations.AddField(
            model_name='cmpquestionnairequestionlinks',
            name='cod_option',
            field=models.ForeignKey(blank=True, db_column='cod_option', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_links', to='questionnaries.cmpquestionoptions'),
        ),
        migrations.AddField(
            model_name='cmpquestionnairequestionlinks',
            name='id_question',
            field=models.ForeignKey(blank=True, db_column='id_question', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='questionnaries.cmpquestion'),
        ),
        migrations.AddField(
            model_name='cmpquestionnairequestionlinks',
            name='id_questionnaire',
            field=models.ForeignKey(blank=True, db_column='id_questionnaire', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_links', to='questionnaries.cmpquestionnaire'),
        ),
        migrations.AddField(
            model_name='cmpquestionnairequestiongroup',
            name='id_questionnaire',
            field=models.ForeignKey(blank=True, db_column='id_questionnaire', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_groups', to='questionnaries.cmpquestionnaire'),
        ),
        migrations.AddField(
            model_name='cmpquestionnaire',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpquestionnaire',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='cmpquestionnaire',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='cmpquestionnaire',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpquestionlistvalues',
            name='id_question',
            field=models.ForeignKey(blank=True, db_column='id_question', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_values', to='questionnaries.cmpquestion'),
        ),
        migrations.AddField(
            model_name='cmpquestionlisttables',
            name='id_question',
            field=models.OneToOneField(blank=True, db_column='id_question', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_table', to='questionnaries.cmpquestion'),
        ),
        migrations.AddField(
            model_name='cmpquestionlang',
            name='cod_language',
            field=models.ForeignKey(db_column='cod_language', on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='masters.mstlanguages'),
        ),
        migrations.AddField(
            model_name='cmpquestionlang',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpquestionlang',
            name='id_question',
            field=models.ForeignKey(blank=True, db_column='id_question', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='questionnaries.cmpquestion'),
        ),
        migrations.AddField(
            model_name='cmpquestionlang',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='cmpquestionlang',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='cmpquestionlang',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpquestionkeywords',
            name='id_question',
            field=models.OneToOneField(blank=True, db_column='id_question', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='questionnaries.cmpquestion'),
        ),
        migrations.AddField(
            model_name='cmpquestion',
            name='cod_question_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='questionnaries.mstquestionclass'),
        ),
        migrations.AddField(
            model_name='cmpquestion',
            name='cod_question_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='questionnaries.mstquestiontype'),
        ),
        migrations.AddField(
            model_name='cmpquestion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpquestion',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='cmpquestion',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='cmpquestion',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='mstquestiontype',
            unique_together={('cod_question_type', 'enu_base_question_type', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='mstquestionclass',
            unique_together={('cod_question_class', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='cmpquestionoptions',
            unique_together={('id_question', 'cod_option')},
        ),
        migrations.AlterUniqueTogether(
            name='cmpquestionnairequestions',
            unique_together={('id_questionnaire', 'id_question', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='cmpquestionnairequestionoptions',
            unique_together={('id_questionnaire', 'id_question', 'id_option')},
        ),
        migrations.AlterUniqueTogether(
            name='cmpquestionnairequestionlinks',
            unique_together={('id_questionnaire', 'id_question', 'cod_option', 'id_linked_question', 'enu_link_type')},
        ),
        migrations.AlterUniqueTogether(
            name='cmpquestionnairequestiongroup',
            unique_together={('id_questionnaire', 'num_question_group')},
        ),
        migrations.AddIndex(
            model_name='cmpquestionnaire',
            index=models.Index(fields=['id_questionnaire'], name='cmp_questio_id_ques_0f6735_idx'),
        ),
        migrations.AddIndex(
            model_name='cmpquestionnaire',
            index=models.Index(fields=['cod_rec_status'], name='cmp_questio_cod_rec_6c4b5d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cmpquestionnaire',
            unique_together={('id_questionnaire', 'cod_rec_status')},
        ),
        migrations.AlterUniqueTogether(
            name='cmpquestionlistvalues',
            unique_together={('id_question', 'cod_value')},
        ),
        migrations.AlterUniqueTogether(
            name='cmpquestionlang',
            unique_together={('id_question', 'cod_language', 'cod_rec_status')},
        ),
    ]
