# Generated by Django 4.2.27 on 2026-03-12 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MstProdCodes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cod_product', models.CharField(max_length=4, unique=True)),
                ('enu_product_type', models.CharField(choices=[('CAS', 'Current & Savings'), ('CRD', 'Credit Card'), ('FD', 'Fixed Deposit'), ('LON', 'Loan'), ('MTG', 'Mortgage'), ('INS', 'Insurance'), ('INV', 'Investment'), ('PEN', 'Pension'), ('OTH', 'Other')], default='CAS', max_length=3)),
                ('txt_product_name', models.CharField(max_length=48)),
                ('dat_prod_offer_start', models.DateField(blank=True, null=True)),
                ('dat_prod_offer_end', models.DateField(blank=True, null=True)),
                ('flg_apply_selfserve_mode', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('flg_sales_certif_reqd', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('flg_e_stmt_avlbl', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('bin_product_brochure', models.CharField(blank=True, max_length=255, null=True)),
                ('bin_product_soc', models.CharField(blank=True, max_length=255, null=True)),
                ('bin_product_mitc', models.CharField(blank=True, max_length=255, null=True)),
                ('txt_mktg_tag_line', models.CharField(blank=True, max_length=255, null=True)),
                ('id_eligibility_questionnaire', models.BigIntegerField(default=0)),
                ('num_eligibility_score_min', models.SmallIntegerField(default=9999)),
                ('txt_gen_appl_num_func', models.CharField(blank=True, max_length=255, null=True)),
                ('txt_gen_acct_num_func', models.CharField(blank=True, max_length=255, null=True)),
                ('flg_default_value', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('cod_rec_status', models.CharField(choices=[('A', 'Active'), ('N', 'New'), ('M', 'Modified'), ('R', 'Reviewed'), ('C', 'Cancelled'), ('X', 'Deleted')], default='A', max_length=1)),
                ('dat_last_maker', models.DateField(blank=True, null=True)),
                ('dat_last_checker', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Product Code',
                'verbose_name_plural': 'Product Codes',
                'db_table': 'mst_prod_codes',
            },
        ),
        migrations.CreateModel(
            name='MstProdDisclosures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_disclosure', models.CharField(max_length=4)),
                ('num_sequence', models.SmallIntegerField(blank=True, null=True)),
                ('flg_all_applicants_mandatory', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('flg_guarantors_mandatory', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('cod_rec_status', models.CharField(choices=[('A', 'Active'), ('N', 'New'), ('M', 'Modified'), ('R', 'Reviewed'), ('C', 'Cancelled'), ('X', 'Deleted')], default='A', max_length=1)),
                ('dat_last_maker', models.DateField(blank=True, null=True)),
                ('dat_last_checker', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Product Disclosure',
                'verbose_name_plural': 'Product Disclosures',
                'db_table': 'mst_prod_disclosures',
            },
        ),
        migrations.CreateModel(
            name='MstProdDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_doc_type', models.CharField(max_length=4)),
                ('enu_doc_purpose', models.CharField(choices=[('I', 'Initiation'), ('A', 'Account Opening'), ('S', 'Submission'), ('C', 'Closure'), ('T', 'Top-up'), ('P', 'Post Disbursement'), ('M', 'Modification'), ('U', 'Updation'), ('F', 'Foreclosure'), ('V', 'Verification'), ('G', 'General')], default='I', max_length=1)),
                ('flg_acct_opening_doc', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('num_days_from_acct_opening', models.SmallIntegerField(default=-1)),
                ('flg_renewal_doc', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('enu_post_disb_resubmit_freq', models.CharField(choices=[('M', 'Monthly'), ('Q', 'Quarterly'), ('H', 'Half-Yearly'), ('A', 'Annually'), ('O', 'Others')], default='X', max_length=1)),
                ('flg_mandatory', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('cod_rec_status', models.CharField(choices=[('A', 'Active'), ('N', 'New'), ('M', 'Modified'), ('R', 'Reviewed'), ('C', 'Cancelled'), ('X', 'Deleted')], default='A', max_length=1)),
                ('dat_last_maker', models.DateField(blank=True, null=True)),
                ('dat_last_checker', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Product Document',
                'verbose_name_plural': 'Product Documents',
                'db_table': 'mst_prod_docs',
            },
        ),
        migrations.CreateModel(
            name='MstPromoCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_promo', models.CharField(max_length=4)),
                ('txt_promo_code_desc', models.CharField(blank=True, max_length=96, null=True)),
                ('flg_default_value', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, null=True)),
                ('dat_promo_start', models.DateField(blank=True, null=True)),
                ('dat_promo_end', models.DateField(blank=True, null=True)),
                ('txt_promo_headline', models.CharField(blank=True, max_length=96, null=True)),
                ('txt_promo_tagline', models.CharField(blank=True, max_length=96, null=True)),
                ('txt_promo_offer_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('bin_promo_creative', models.CharField(blank=True, max_length=255, null=True)),
                ('bin_promo_creative_small', models.CharField(blank=True, max_length=255, null=True)),
                ('flg_customer_facing', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1, null=True)),
                ('num_promo_priority', models.SmallIntegerField(blank=True, null=True)),
                ('cod_rec_status', models.CharField(choices=[('A', 'Active'), ('N', 'New'), ('M', 'Modified'), ('R', 'Reviewed'), ('C', 'Cancelled'), ('X', 'Deleted')], default='A', max_length=1)),
                ('dat_last_maker', models.DateField(blank=True, null=True)),
                ('dat_last_checker', models.DateField(blank=True, null=True)),
                ('cod_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='product.mstprodcodes')),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
                'db_table': 'mst_promo_codes',
            },
        ),
    ]
