name: Deploy Django Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        port: 22
        script: |
          cd ~/Demo_Project-Satisactual

          echo "Pull latest code"
          git pull origin main

          echo "Stop containers"
          docker-compose down

          echo "Build containers"
          docker-compose build

          echo "Start containers"
          docker-compose up -d